.\" Man page for LightMdEditor
.\" Contact ask@bhavyanshu.me
.TH LightMdEditor 1 "07 Nov 2014"
.SH NAME
LightMdEditor \- Markdown Editor
.SH SYNOPSIS
LightMdEditor is a markdown editor based on Qt and C++.
.SH DESCRIPTION
 It is a feature rich markdown editor with syntax highlighting, focus
 mode, distraction free mode and has easy shortcuts keys for various 
 markdown tags. It also supports all your system fonts.
 It is licensed under GPLv3. See COPYING file for more information.
.SH OPTIONS
No options for this man page
.SH SEE ALSO
man(1), groff(1), man.config(5)
.SH BUGS
If you find a bug, please report it at below address.
.SH AUTHOR
Bhavyanshu Parasher (ask@bhavyanshu.me)
